<?php

return [
    'books' => [
        'battle-ready-laravel' => 'https://battle-ready-laravel.com/?aff=WJ9DG',
        'consuming-apis-laravel' => 'https://consuming-apis-in-laravel.com/?aff=WJ9DG',
        'domain-driven-laravel' => 'https://martinjoo.gumroad.com/l/ddd-laravel-premium?a=266251475',
        'level-up-tailwind-css' => 'https://shrutibalasa.gumroad.com/l/level-up-with-tailwind-css?a=266251475',
        'mastering-laravel-validation-rules' => 'https://nocompromises.gumroad.com/l/laravel-validation?a=266251475',
        'microservices-laravel' => 'https://martinjoo.gumroad.com/l/microservices-with-laravel-premium?a=266251475',
        'vue-design-patterns' => 'https://lachlanmiller.gumroad.com/l/vuejs-design-patterns?a=266251475',
        'best-practices-laravel-enterprise-apps' => 'https://gumroad.com/a/708015763/vtxqpk',
    ],

    'courses' => [
        'serverless-laravel' => 'https://jackellis.gumroad.com/l/serverlesslaravel?a=266251475',
    ],

    'services' => [
        'aesirx' => 'https://aesirx.io/',
        'cleanmymac' => 'https://macpaw.audw.net/c/3801334/3398815/1733?u=https%3A%2F%2Fmacpaw.com%2Fcleanmymac',
        'crazy-egg' => 'https://www.crazyegg.com/',
        'clicky' => 'https://clicky.com/',
        'cloudways-php' => 'https://www.cloudways.com/en/php-hosting.php?id=1242932',
        'cloudways' => 'https://www.cloudways.com/en/laravel-hosting?id=1242932',
        'codecademy' => 'https://www.pjtra.com/t/2-438168-292025-213588',
        'digitalocean-managed-databases' => 'https://digitalocean.pxf.io/c/3801334/1377288/15890',
        'digitalocean-managed-mysql-database' => 'https://digitalocean.pxf.io/baNjbB',
        'digitalocean' => 'https://digitalocean.pxf.io/c/3801334/1377286/15890',
        'fathom-analytics' => 'https://usefathom.com/ref/JTPOCN',
        'flare' => 'https://flareapp.io/?via=benjamincrozat',
        'headshotpro' => 'https://www.headshotpro.com/?via=benjamincrozat',
        'hostgator' => 'https://partners.hostgator.com/Py6kbX',
        'hotjar' => 'https://www.hotjar.com/',
        'kissmetrics' => 'https://www.kissmetrics.io/',
        'kinsta' => 'https://kinsta.com/application-hosting/?kaid=AEFAUTRRTINA',
        'magicpost' => 'https://go.magicpost.in/benjamin-crozat',
        'mailcoach' => 'https://mailcoach.app/?via=benjamincrozat',
        'mouseflow' => 'https://mouseflow.com/',
        'namecheap' => 'https://namecheap.pxf.io/c/3801334/1712998/5618',
        'oh-dear' => 'https://ohdear.app/?via=benjamincrozat',
        'ploi' => 'https://ploi.io/register?referrer=eJAat2H4YE45BjmIwzBl',
        'rosehosting' => 'https://secure.rosehosting.com/clientarea/?affid=2695&campaign=dedicated-hosting',
        'savvycal' => 'https://savvycal.com/?via=benjamincrozat',
        'semrush' => 'https://semrush.sjv.io/benjamincrozat',
        'setapp' => 'https://setapp.sjv.io/c/3801334/344537/5114',
        'similarweb' => 'https://www.similarweb.com/',
        'simple-analytics' => 'https://simpleanalytics.com/?referral=benjamincrozat',
        'skillshare' => 'https://skillshare.eqcm.net/rQWAbD',
        'tinkerwell' => 'https://tinkerwell.app/?ref=benjamincrozat',
        'tower' => 'https://www.git-tower.com/?via=benjamincrozat',
        'uptimia' => 'https://www.uptimia.com/?via=benjamincrozat',
        'untitled-ui' => 'https://store.untitledui.com?aff=WJ9DG',
        'usermaven' => 'https://usermaven.com/',
        'vultr' => 'https://www.vultr.com/products/cloud-compute/?ref=9270910-8H',
        'webshare' => 'https://www.webshare.io/?referral_code=dt6d6ofk1rzp',
        'wincher' => 'https://www.wincher.com/rank-tracker?via=benjamincrozat',
    ],
];
